List<List<dynamic>> allIndustries = [
  [
    "assets/images/icon_agri.png",
    "assets/images/icon_animal.png",
    "assets/images/icon_beauty.png",
    "assets/images/icon_food.png",
    "assets/images/icon_glass.png",
    "assets/images/icon_leather.png",
    "assets/images/icon_metal.png",
    "assets/images/icon_paint.png",
    "assets/images/icon_palm_deriv.png",
    "assets/images/icon_pharmacy.png",
    "assets/images/icon_pine_deriv.png",
    "assets/images/icon_plastic.png",
    "assets/images/icon_pulp.png",
    "assets/images/icon_rubber.png",
    "assets/images/icon_soap.png",
    "assets/images/icon_surplus.png",
    "assets/images/icon_textile.png",
    "assets/images/icon_water.png",
    "assets/images/icon_textile.png",
    "assets/images/icon_water.png",
  ],
];

// detail products item
List<List<String>> detailProductsItem = [
  [
    "P.I Number",
    "Customer Name",
    "POL",
    "POD",
    "Qty",
    "AWB",
    "ETD",
    "ETA",
    "B/L Number"
  ],
  [
    "PI/TI/221110703/2022",
    "Amelia Azzahra",
    "Any Port in Vietnam",
    "Chattogram, Bangladesh",
    "84,00 MT",
    "...",
    "2023/01/17 13:00 PM",
    "2023/01/31 13:00 PM",
    "...",
  ],
];

// detail quotations
List<List<String>> detailQuotations = [
  [
    "First Name",
    "Last Name",
    "Phone Number",
    "Country",
    "Company Name",
    "Product Name",
    "Quantity",
    "Unit",
    "Incoterm",
    "Port of Destination",
    "Message",
  ],
  [
    "Dimas",
    "Pradipta",
    "(+62) 885691410815",
    "Bangladesh",
    "Tradeasia International",
    "DIpentene",
    "800",
    "Tone",
    "FOB",
    "Any port in Vietnam",
    "...",
  ],
];

/* Contact Us Data */
List<List<String>> contactUsData = [
  [
    "TRADEASIA INTERNATIONAL PTE LTD (Headquarters)",
    "TRADEASIA INTERNATIONAL DMCC (Dubai)",
    "TRADEASIA INTERNATIONAL PVT. LTD (Mumbai)",
    "TRADEASIA INTERNATIONAL PVT. LTD (Chennai)",
    "PT SREE INTERNATIONAL INDONESIA (Jakarta)",
    "TRADEASIA INTERNATIONAL NANJING.CO.LTD (Nanjing)",
    "TRADEASIA INTERNATIONAL PTE.LTD. (Sri Lanka)",
    "TRADEASIA INTERNATIONAL PTE.LTD. (Sri Lanka)",
    "TRADEASIA INTERNATIONAL PTE LTD (Seoul)",
    "TRADEASIA INTERNATIONAL PTE LTD (Bangkok)",
    "TRADEASIA INTERNATIONAL PTE LTD PHILIPPINES REP. OFFICE (Manila)",
  ],
  [
    "	+65-62276365",
    "	+971 4 2778045",
    "	+912261231800",
    "	+	+912261231800",
    "	+62 21 50806560",
    "	+86 2183210364",
    "	+94 117444152 / +94 767013435",
    "	+84 8 3827 7218/19",
    "	+82 2 556 2027",
    "	+662-656-0500 (Ext: 103)",
    "	+63 25179301"
  ],
  [
    "singapore@chemtradeasia.com",
    "dubai@chemtradeasia.com",
    "india@chemtradeasia.com",
    "india@chemtradeasia.com",
    "indonesia@chemtradeasia.com",
    "contact@chemtradeasia.com",
    "srilanka@chemtradeasia.com",
    "vietnam@chemtradeasia.com",
    "korea@chemtradeasia.com",
    "thailand@chemtradeasia.com",
    "philippines@chemtradeasia.com",
  ],
  [
    "133 Cecil Street #12-03 Keck Seng Tower, Singapore 069535",
    "Unit No: 1807 Fortune Executive Tower Plot No: JLT-PH2-T1A, Jumeriah Lakes Tower Dubai, UAE",
    "503/504, 5th Floor Kanakia Atrium 2 Andheri-Kurla Rd - Andheri East, Mumbai 400093",
    "Office No 210 DBS HOUSE Cathedral Gardens Road Nungambakkam, Chennai 600034",
    "Sopodel Tower, Tower B Lantai - 9 Jl.Mega Kuningan Barat III RT.5/RW.5, Kuningan Timur, Setiabudi, South Jakarta -12950 Republic of Indonesia",
    "Room 918 Golden Wheel Building, No.8 - Hanzhong Lu Gulou District, Nanjing China - 210000",
    "2nd Floor, McLarens Building, No 123 Bauddhaloka Mawatha, Colombo 04, Sri Lanka",
    "Unit G, 3rd Floor VTP Office Building, No. 8 Nguyen Hue Blvd, Ben Nghe Ward, District 1 Ho Chi Minh, Vietnam",
    "F Namjeon Building,326, 8 Bongeunsa-ro, Gangnam-gu Seoul - 06143, Republic of Korea",
    "973 President Tower 11th Floor Room 103, Ploenchit Road Lumpini, Pathumwan, Thailand - 10330",
    "CEO Suite Manila 37F LKG tower 6801 Ayala Avenue Makati City, 1226 Philippines",
  ],
];
