import 'package:mytradeasia/view/menu/all_products/all_industry_screen.dart';

// iconModel for homescreen
List iconModel = [
  "assets/images/icon_agri.png",
  "assets/images/icon_animal.png",
  "assets/images/icon_beauty.png",
  "assets/images/icon_food.png",
  "assets/images/icon_glass.png",
  "assets/images/icon_leather.png",
  "assets/images/icon_metal.png",
  "assets/images/icon_all_industry.png",
];

// iconName for homescreen
List iconName = [
  "Agriculture",
  "Animal Feed",
  "Beauty & Personal Care",
  "Food & Beverage",
  "Glass & Ceramic",
  "Leather",
  "Metal & Steel",
  "All Industries",
];

// url for homescreen
List urlNavigator = [
  const AllIndustryScreen(),
  const AllIndustryScreen(),
  const AllIndustryScreen(),
  const AllIndustryScreen(),
  const AllIndustryScreen(),
  const AllIndustryScreen(),
  const AllIndustryScreen(),
  const AllIndustryScreen(),
];

List<List<dynamic>> allIndustries = [
  [
    "Agriculture",
    "Animal Feed",
    "Beauty & Personal Care",
    "Food & Beverage",
    "Glass & Ceramic",
    "Leather",
    "Metal & Steel",
    "Paint, Ink & Coating",
    "Palm Derivative",
    "Pharmacheutical",
    "Pine Derivative",
    "Plastic &  Polymer",
    "Pulp & Paper",
    "Rubber",
    "Soap & Detergent",
    "Surplus Chemicals",
    "Textile",
    "Water Treatment",
  ],
  [
    "assets/images/icon_agri.png",
    "assets/images/icon_animal.png",
    "assets/images/icon_beauty.png",
    "assets/images/icon_food.png",
    "assets/images/icon_glass.png",
    "assets/images/icon_leather.png",
    "assets/images/icon_metal.png",
    "assets/images/icon_paint.png",
    "assets/images/icon_palm_deriv.png",
    "assets/images/icon_pharmacy.png",
    "assets/images/icon_pine_deriv.png",
    "assets/images/icon_plastic.png",
    "assets/images/icon_pulp.png",
    "assets/images/icon_rubber.png",
    "assets/images/icon_soap.png",
    "assets/images/icon_surplus.png",
    "assets/images/icon_textile.png",
    "assets/images/icon_water.png",
  ],
  // [
  //   "assets/images/icon_agri.png",
  //   "assets/images/icon_animal.png",
  //   "assets/images/icon_beauty.png",
  //   "assets/images/icon_food.png",
  //   "assets/images/icon_glass.png",
  //   "assets/images/icon_leather.png",
  //   "assets/images/icon_metal.png",
  //   "assets/images/icon_paint.png",
  //   "assets/images/icon_palm_deriv.png",
  //   "assets/images/icon_pharmacy.png",
  //   "assets/images/icon_pine_deriv.png",
  //   "assets/images/icon_plastic.png",
  //   "assets/images/icon_pulp.png",
  //   "assets/images/icon_rubber.png",
  //   "assets/images/icon_soap.png",
  //   "assets/images/icon_surplus.png",
  //   "assets/images/icon_textile.png",
  //   "assets/images/icon_water.png",
  // ],
];
