// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsYM6v81BJU2Smb6ChZIZTyA-9XLnTwuM',
    appId: '1:476020516162:web:4dcaf78ce0e5b38812d4db',
    messagingSenderId: '476020516162',
    projectId: 'mytradeasia-920d9',
    authDomain: 'mytradeasia-920d9.firebaseapp.com',
    storageBucket: 'mytradeasia-920d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO52FymUZwFloag66mv0ybeU9vnmLwdTk',
    appId: '1:476020516162:android:c1eda88b3f3573c312d4db',
    messagingSenderId: '476020516162',
    projectId: 'mytradeasia-920d9',
    storageBucket: 'mytradeasia-920d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAES0_4lDUn93zSOR7rJBJhwWYXDrCLSXc',
    appId: '1:476020516162:ios:d1667dcc83d83bc512d4db',
    messagingSenderId: '476020516162',
    projectId: 'mytradeasia-920d9',
    storageBucket: 'mytradeasia-920d9.appspot.com',
    iosClientId: '476020516162-qs8v2h8vr3fhuubj5hnj1s0ijd991elp.apps.googleusercontent.com',
    iosBundleId: 'com.example.mytradeasia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAES0_4lDUn93zSOR7rJBJhwWYXDrCLSXc',
    appId: '1:476020516162:ios:d1667dcc83d83bc512d4db',
    messagingSenderId: '476020516162',
    projectId: 'mytradeasia-920d9',
    storageBucket: 'mytradeasia-920d9.appspot.com',
    iosClientId: '476020516162-qs8v2h8vr3fhuubj5hnj1s0ijd991elp.apps.googleusercontent.com',
    iosBundleId: 'com.example.mytradeasia',
  );
}
